# Experiment Settings
wandb_project: gemma2-2b
wandb_run_name: gated
wandb_tags: ["gated"]
seed: 42

# Model Configuration  
tlens_model_name: "google/gemma-2-2b" 
tlens_model_path: null
dtype: bfloat16
use_torch_compile: true
torch_compile_mode: "reduce-overhead"  

# Training Configuration
save_every_n_samples: 100_000
eval_every_n_samples: 20_000
gradient_accumulation_steps: 1
lr: 3e-4
lr_schedule: cosine
min_lr_factor: 0.1
warmup_samples: 20_000
max_grad_norm: 10.0
log_every_n_grad_steps: 20

# Data Configuration
data:
  dataset_name: "chanind/pile-uncopyrighted-gemma-1024-abbrv-1B"
  tokenizer_name: "google/gemma-2-2b"
  context_length: 1024
  n_train_samples: 500_000
  n_eval_samples: 1_000
  train_batch_size: 8
  eval_batch_size: 8
  streaming: true
  seed: null
  is_tokenized: true
  column_name: "input_ids"
  split: "train"

# SAE Configuration - Gated SAE
saes:
  name: "gated_sae"
  sae_type: "gated"
  dict_size_to_input_ratio: null
  n_dict_components: 16384
  magnitude_activation: "relu"
  magnitude_encoder: 'scale'
  pretrained_sae_paths: null
  retrain_saes: false
  sae_positions:
    - blocks.12.hook_resid_pre
  init_decoder_orthogonal: true
  sparsity_coeff: 0.1
